### ISSUE TITLE
Build Error

### ISSUE THREAD

**Issue by DaveTheOne** [OpenEmu/Play-Core#1]
Code is not complete. Missing OEPS2SystemResponderClient.h! Can't compile and evaluate this core with OpenEmu.

**Comment by clobber** [comment]
It isn't ready to be evaluated.

**Comment by mrvacbob** [comment]
Hmmm this is kinda valid. The core is not playable but it is develop-able (if you're a Play! dev at least).

The project is only set up to be built from inside OpenEmu.xcworkspace, and it's not ready to be added there, which is why you'd see this error.

**Comment by DaveTheOne** [comment]
I know how to setup (add other cores) the project in order to compile everything. The point is that the project is not complete. Core in this context means some wrapper classes, an asset folder and external sources. So no Play! development but "Wrapper" (Core) development.

**Comment by clobber** [comment]
>The point is that the project is not complete.

Hey I think we're all making the same point!

**Comment by DaveTheOne** [comment]
Just to let you know. Got it working. Looked a bit closer at project structure and found everything. Now only dolphin core is missing. Actual fork does not contain all files but cyco fork looks not to bad.

**Comment by clobber** [comment]
Uh, congratulations I guess?

These very-alpha core ports are not included and set up in the workspace for a reason.
