### ISSUE TITLE
Couldn't communicate with helper application

### ISSUE THREAD

**Issue by WeedyWeedSmoker** [OpenEmu/Play-Core#4]
I compiled this pre-release core with success, but this message pops up : Couldn't communicate with helper application...

All the other cores I compiled or downloaded from here/inside the app are working fine, except from the 2 latest mednafen core updates, which give the same message...

I'll file an issue report to the Mednafen core issues tracker too...

**Comment by clobber** [comment]
This port isn't ready or supported yet.

These very-alpha core ports are not included and set up in the workspace for a reason.
